In [1]:
# Definition: Variables are used to store and manage data in a program.
age = 25
print("Votre âge est :", age)

Votre âge est : 25


In [2]:
# Definition: Conditions are used to make decisions in a program.
age = 25
if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")

You are an adult.


In [3]:
# Boucle for pour itérer sur une liste
fruits = ["pomme", "banane", "orange"]
for fruit in fruits:
    print(fruit)

# Boucle while pour exécuter un bloc de code tant qu'une condition est vraie
num = 1
while num <= 5:
    print(num)
    num += 1

pomme
banane
orange
1
2
3
4
5


In [4]:
# Definition: Functions are blocks of reusable code that perform a specific task.
def greet(name):
    print("Hello, " + name + "!")

greet("Alice")  # Example: Calling the function greet with the argument "Alice"

Hello, Alice!


In [5]:
# Definition: Lists are ordered and mutable collections in Python.
numbers = [1, 2, 3, 4, 5]  # Example: Creating a list of numbers
fruits = ["apple", "orange", "banana"]  # Example: Creating a list of strings

In [6]:
# Definition: Tuples are ordered and immutable collections.
coordinates = (3, 4)  # Example: Creating a tuple with coordinates
colors = ("red", "green", "blue")  # Example: Creating a tuple of colors

In [7]:
# Definition: Dictionaries are unordered collections of key-value pairs.
person = {"name": "John", "age": 30, "city": "New York"}  # Example: Creating a dictionary

In [8]:
# Definition: The os module provides a way to interact with the operating system.
import os
current_directory = os.getcwd()  # Example: Getting the current working directory
print(current_directory)

C:\Users\DELL\IA2


In [9]:
# Definition: The math module provides mathematical functions and constants.
import math
result = math.sqrt(25)  # Example: Calculating the square root using math.sqrt()
print(result)


5.0


In [10]:
# Definition: The random module is used for generating random numbers.
import random
random_number = random.randint(1, 10)  # Example: Generating a random integer between 1 and 10
print(random_number)

7


In [11]:
# Definition: The re module stands for regular expressions.
import re
pattern = re.compile(r'\b\w+\b')  # Example: Using a regular expression pattern
result = pattern.findall("This is a sample sentence.")
print(result)

['This', 'is', 'a', 'sample', 'sentence']


In [12]:
# Create Lists (Arrays)
# Definition: Lists can be used as a basic alternative to arrays in Python.
list_1d = [1, 2, 3]  # Creating a 1D list

# Execution
print("1D List:", list_1d)

1D List: [1, 2, 3]


In [13]:
# Definition: Creating a 2D list
list_2d = [[1, 2, 3], [4, 5, 6]]


print("2D List:")
for row in list_2d:
    print(row)

2D List:
[1, 2, 3]
[4, 5, 6]


In [14]:
# Indexing Lists
# Definition: Accessing elements or sublists within a list using index or slicing.
element = list_1d[1]  # Accessing elements in a 1D list


print("Indexed Element:", element)

Indexed Element: 2


In [15]:
# Broadcasting (with Loops)
# Definition: Achieving broadcasting-like behavior using loops with lists.
scaled_list = [x * 2 for x in list_1d]  # Broadcasting with a scalar

# Execution
print("Scaled List:", scaled_list)

# Definition: Broadcasting with lists of different shapes using loops
sum_list = [[x + y for x, y in zip(row, [10, 20, 30])] for row in list_2d]

# Execution
print("Sum List:")
for row in sum_list:
    print(row)

Scaled List: [2, 4, 6]
Sum List:
[11, 22, 33]
[14, 25, 36]


In [16]:
# Copy (Deep Copy)
# Definition: Creating a deep copy of a list.
list_copy = list_1d.copy()  # Creating a copy of a list

# Execution
print("Copied List:", list_copy)

Copied List: [1, 2, 3]


In [17]:
# View (Shallow Copy)
# Definition: Creating a shallow copy (view) of a list.
list_view = list_2d[:]  # Creating a view of a list

# Execution
print("Viewed List:")
for row in list_view:
    print(row)

Viewed List:
[1, 2, 3]
[4, 5, 6]


In [18]:
import numpy as np

def backpropagation(X, Y, W1, b1, W2, b2, learning_rate):
    # Forward pass
    z1 = np.dot(W1, X) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(W2, a1) + b2
    y_pred = sigmoid(z2)
    
    # Compute error
    error = y_pred - Y
    
    # Backward pass
    delta2 = error * sigmoid_derivative(y_pred)
    delta1 = np.dot(W2.T, delta2) * sigmoid_derivative(z1)
    
    # Update weights and biases
    W2 -= learning_rate * np.dot(delta2, a1.T)
    b2 -= learning_rate * np.sum(delta2, axis=1, keepdims=True)
    W1 -= learning_rate * np.dot(delta1, X.T)
    b1 -= learning_rate * np.sum(delta1, axis=1, keepdims=True)
    
    return W1, b1, W2, b2

# Assurez-vous d'avoir défini les fonctions sigmoid et sigmoid_derivative

# Exemple d'utilisation dans la fonction train_neural_network
def train_neural_network(X, Y, input_size, hidden_size, output_size, learning_rate, num_epochs):
    W1, b1 = initialize_parameters(input_size, hidden_size)
    W2, b2 = initialize_parameters(hidden_size, output_size)
    
    for epoch in range(num_epochs):
        W1, b1, W2, b2 = backpropagation(X, Y, W1, b1, W2, b2, learning_rate)
    
    return W1, b1, W2, b2

In [19]:
import numpy as np

def update_weights(learning_rate, error_term, input_values, weights, biases):
    # Compute weight update
    delta_weights = learning_rate * np.outer(error_term, input_values)
    
    # Update weights
    updated_weights = weights + delta_weights
    
    # Compute bias update
    delta_bias = learning_rate * error_term
    
    # Update biases
    updated_biases = biases + delta_bias.reshape(-1, 1)
    
    return updated_weights, updated_biases

# Exemple d'utilisation
learning_rate = 0.01
error_term = np.array([0.1, 0.2, 0.3])
input_values = np.array([1, 2])
weights_old = np.random.rand(3, 2)  
biases_old = np.random.rand(3, 1)  

updated_weights, updated_biases = update_weights(learning_rate, error_term, input_values, weights_old, biases_old)

print("Updated Weights:\n", updated_weights)
print("Updated Biases:\n", updated_biases)

Updated Weights:
 [[0.90133947 0.98526504]
 [0.67583191 0.80019285]
 [0.57791879 0.59439384]]
Updated Biases:
 [[0.65531487]
 [0.61283904]
 [0.91376406]]


In [20]:
import numpy as np

def compute_error(xi, yt, error, W, is_output_layer=True):
    if is_output_layer:
        # Compute error for the output layer
        ei = xi * (1 - yt) * error
        return ei
    else:
        # Compute error for a hidden layer
        ek_i = xi * (1 - xi) * np.dot(W.T, error)
        return ek_i

# Example usage
xi = np.array([0.1, 0.2, 0.3])  # Replace with your actual input
yt = 0.8  # Replace with your actual target output
error = 0.1  # Replace with your actual error
W = np.random.rand(3, 2)  # Replace with your actual weights

# Assuming it's the output layer
output_layer_error = compute_error(xi, yt, error, W, is_output_layer=True)
print("Output Layer Error:", output_layer_error)

# Assuming it's a hidden layer
hidden_layer_error = compute_error(xi, yt, error, W, is_output_layer=False)
print("Hidden Layer Error:", hidden_layer_error)

Output Layer Error: [0.002 0.004 0.006]
Hidden Layer Error: [[0.00203441 0.01186067 0.01374801]
 [0.00396273 0.00659158 0.01334443]]
